function C1yauzaelcetronosc00003 = importfileVolt(filename, dataLines)
%IMPORTFILE Import data from a text file
%  C1YAUZAELCETRONOSC00003 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  C1YAUZAELCETRONOSC00003 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  C1yauzaelcetronosc00003 = importfile("\\vmware-host\Shared Folders\proj\GraphPlotOctave\arsa\C1yauza_elcetron_osc00003.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Aug-2020 07:56:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "TrigTime", "Var3"];
opts.SelectedVariableNames = "TrigTime";
opts.VariableTypes = ["string", "double", "string"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TrigTime", "TrimNonNumeric", true);
opts = setvaropts(opts, "TrigTime", "DecimalSeparator", ".");
opts = setvaropts(opts, "TrigTime", "ThousandsSeparator", ",");

% Import the data
C1yauzaelcetronosc00003 = readtable(filename, opts);

%% Convert to output type
C1yauzaelcetronosc00003 = table2array(C1yauzaelcetronosc00003);
end